version: '3.8'

services:
  web-php_db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./docker_tmp/mysql_data:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: f23Ur23D
      MYSQL_DATABASE: gtree
      MYSQL_USER: gtreeu
      MYSQL_PASSWORD: jET3E4W9vm
    networks:
      - family_tree_net

  web-cpp:
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - "88:80"
    #   - "88:10555"
    volumes:
      - ./data:/root/data
    networks:
      - family_tree_net
    restart: always

  web-php:
    build:
      context: .
      dockerfile: Dockerfile.php
    ports:
      - "88:80"
    volumes:
      - ./www:/var/www/html
      - ./docker_tmp/log:/var/log/apache2
    networks:
      - family_tree_net
    restart: always
    depends_on:
      - web-cpp
      - web-php_db

networks:
  family_tree_net:
    driver: bridge